'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,ChevronDown,Copy,FileCode2,History,Loader2,Monitor,AlertCircle,Plug,RotateCcw,Settings2,Sparkles,Square,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {DEFAULT_OLLAMA_URL,connectionError,listOllamaModels,ollamaUrl} from '@/lib/ollama';
import {runHtmlAgent} from '@/lib/html-agent';
import type {AgentStep} from '@/lib/agent-types';
import type {HtmlEdit} from '@/lib/html-workspace';
import type {Mockup,MockupPreview,Revision,Screen} from '@/lib/types';

type Props={mockup:Mockup;html:string|undefined;ready:boolean;author:string;screenName:string;tab:'ai'|'history'|null;preview:MockupPreview|null;onTab:(tab:'ai'|'history'|null)=>void;onPreview:(preview:MockupPreview|null)=>void;onApplied:(value:{html:string;revision:number;screens:Screen[]})=>void};
type Candidate={summary:string;edits:HtmlEdit[];checkedScreens:number;html:string;screens:Screen[];prompt:string;model:string;baseRevision:number;requestId:string};
const date=(value:number)=>new Date(value).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});

export default function MockupEditor({mockup,html,ready,author,screenName,tab,preview,onTab,onPreview,onApplied}:Props){
 const [address,setAddress]=useState(DEFAULT_OLLAMA_URL),[model,setModel]=useState(''),[models,setModels]=useState<string[]>([]);
 const [connected,setConnected]=useState(false),[checking,setChecking]=useState(false),[settingsOpen,setSettingsOpen]=useState(true);
 const [prompt,setPrompt]=useState(''),[generating,setGenerating]=useState(false),[steps,setSteps]=useState<AgentStep[]>([]),[candidate,setCandidate]=useState<Candidate|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[connectionIssue,setConnectionIssue]=useState('');
 const [history,setHistory]=useState<Revision[]>([]),[historyLoading,setHistoryLoading]=useState(false),[namedOnly,setNamedOnly]=useState(false),[nextBefore,setNextBefore]=useState<number|null>(null);
 const [nameTarget,setNameTarget]=useState<number|null>(null),[versionName,setVersionName]=useState('');
 const controller=useRef<AbortController|null>(null),mounted=useRef(true),historyRequest=useRef(0);
 const [origin,setOrigin]=useState('https://speckmaker-review.helloooo33.chatgpt.site');
 useEffect(()=>{mounted.current=true;setOrigin(location.origin);try{const saved=JSON.parse(localStorage.getItem('speck-ollama')||'null');if(saved?.url)setAddress(saved.url);if(saved?.model)setModel(saved.model);}catch{}return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
 const loadHistory=useCallback(async(append=false,before?:number)=>{
  const request=++historyRequest.current;setHistoryLoading(true);
  try{const response=await fetch(`/api/mockups/${encodeURIComponent(mockup.id)}/revisions?named=${namedOnly?1:0}${before!==undefined?'&before='+before:''}`,{cache:'no-store'});const data=await response.json() as {history:Revision[];nextBefore:number|null;error?:string};if(!response.ok)throw Error(data.error);if(request!==historyRequest.current||!mounted.current)return;setHistory(previous=>append?[...previous,...data.history.filter(r=>!previous.some(p=>p.id===r.id))]:data.history);setNextBefore(data.nextBefore);}
  catch(e){if(mounted.current&&request===historyRequest.current)setError(connectionError(e));}finally{if(mounted.current&&request===historyRequest.current)setHistoryLoading(false);}
 },[mockup.id,namedOnly]);
 useEffect(()=>{if(tab==='history')loadHistory();},[tab,mockup.revision,loadHistory]);
 async function connect(){setChecking(true);setConnectionIssue('');setError('');try{const normalized=ollamaUrl(address);const found=await listOllamaModels(normalized);if(!mounted.current)return;setModels(found);if(!found.length)throw Error('설치된 모델이 없어요. Ollama에 모델을 설치한 뒤 다시 연결해 주세요.');const selected=found.includes(model)?model:found.find(n=>/qwen.*coder|qwen/i.test(n))||found[0];setModel(selected);setAddress(normalized);setConnected(true);setSettingsOpen(false);try{localStorage.setItem('speck-ollama',JSON.stringify({url:normalized,model:selected}));}catch{}}catch(e){if(mounted.current){setConnected(false);setConnectionIssue(connectionError(e));}}finally{if(mounted.current)setChecking(false);}}
 function selectModel(value:string){setModel(value);try{localStorage.setItem('speck-ollama',JSON.stringify({url:address,model:value}));}catch{}}
 async function generate(){
  if(!html||!ready||!prompt.trim()||!connected||generating)return;
  const abort=new AbortController();controller.current=abort;setGenerating(true);setError('');setSteps([]);setCandidate(null);onPreview(null);
  const baseRevision=mockup.revision,source=html,requestPrompt=prompt.trim(),selectedModel=model;const timeout=setTimeout(()=>abort.abort(new DOMException('생성 시간이 초과됐어요. 다시 시도해 주세요.','TimeoutError')),600000);
  try{const result=await runHtmlAgent({url:address,model:selectedModel,html:source,prompt:requestPrompt,screenName,fileName:mockup.name,signal:abort.signal,onStep:step=>{if(mounted.current)setSteps(previous=>previous.some(s=>s.id===step.id)?previous.map(s=>s.id===step.id?step:s):[...previous,step]);}});if(!mounted.current||abort.signal.aborted)return;
   const draft={html:result.html,screens:result.screens,summary:result.summary,edits:result.edits,checkedScreens:result.validation.screens.length,prompt:requestPrompt,model:selectedModel,baseRevision,requestId:crypto.randomUUID()};setCandidate(draft);onPreview({mockupId:mockup.id,html:result.html,screens:draft.screens,title:'AI 수정안 · 적용 전',kind:'ai'});}

  catch(e){if(!mounted.current)return;if(abort.signal.aborted){if(abort.signal.reason?.name==='TimeoutError')setError('생성 시간이 초과됐어요. 수정 범위를 줄이거나 다른 모델을 선택해 주세요.');else setNotice('생성을 중단했어요. 현재 목업은 그대로입니다.');}else setError(connectionError(e));}
  finally{clearTimeout(timeout);if(mounted.current){setGenerating(false);setSteps(previous=>previous.map(step=>step.status==='running'?{...step,status:'error',detail:abort.signal.aborted?'작업이 중단되었습니다.':'작업을 마무리하지 못했습니다.'}:step));}controller.current=null;}
 }
 async function post(payload:Record<string,unknown>){const response=await fetch(`/api/mockups/${encodeURIComponent(mockup.id)}/revisions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as {html:string;revision:number;screens:Screen[];error?:string};if(!response.ok)throw Error(data.error||'저장하지 못했어요. 다시 시도해 주세요.');return data;}
 async function apply(){if(!candidate||busy)return;setBusy(true);setError('');try{const saved=await post({action:'apply',html:candidate.html,screens:candidate.screens,prompt:candidate.prompt,model:candidate.model,requestId:candidate.requestId,expectedRevision:candidate.baseRevision,author});if(!mounted.current)return;onApplied(saved);setCandidate(null);onPreview(null);setNotice(`변경 #${saved.revision}에 자동 저장했어요.`);}catch(e){if(mounted.current)setError(connectionError(e));}finally{if(mounted.current)setBusy(false);}}
 async function inspectRevision(item:Revision){setBusy(true);setError('');try{const response=await fetch(`/api/mockups/${encodeURIComponent(mockup.id)}?revision=${item.revision}`,{cache:'no-store'});const data=await response.json() as {html:string;screens:Screen[];error?:string};if(!response.ok)throw Error(data.error);if(mounted.current)onPreview({mockupId:mockup.id,html:data.html,screens:data.screens,title:item.label?`v${item.version_number} · ${item.label}`:`변경 #${item.revision}`,kind:'revision',revision:item.revision});}catch(e){if(mounted.current)setError(connectionError(e));}finally{if(mounted.current)setBusy(false);}}
 async function restore(){if(preview?.kind!=='revision'||preview.revision===undefined||busy)return;setBusy(true);setError('');try{const saved=await post({action:'restore',targetRevision:preview.revision,expectedRevision:mockup.revision,requestId:crypto.randomUUID(),author});if(!mounted.current)return;onApplied(saved);onPreview(null);setCandidate(null);setNotice(`복원한 내용을 변경 #${saved.revision}에 저장했어요.`);await loadHistory();}catch(e){if(mounted.current)setError(connectionError(e));}finally{if(mounted.current)setBusy(false);}}
 async function saveVersion(){if(nameTarget===null||!versionName.trim()||busy)return;setBusy(true);setError('');try{await post({action:'version',targetRevision:nameTarget,label:versionName.trim()});if(!mounted.current)return;setNameTarget(null);setVersionName('');setNotice('이름을 붙여 버전으로 저장했어요.');await loadHistory();}catch(e){if(mounted.current)setError(connectionError(e));}finally{if(mounted.current)setBusy(false);}}
 const command=`OLLAMA_ORIGINS="${origin}" ollama serve`;
 const conflict=candidate&&candidate.baseRevision!==mockup.revision;
 if(!tab)return null;
 return <aside className="mockup-editor" aria-label={tab==='ai'?'AI 목업 수정':'변경 이력과 버전'}>
  <header className="editor-panel-header"><div><span className="editor-panel-icon">{tab==='ai'?<Sparkles size={18}/>:<History size={18}/>}</span><h2>{tab==='ai'?'AI로 다듬기':'변경 이력'}</h2></div><Button variant="ghost" size="icon-sm" aria-label="편집 패널 닫기" onClick={()=>onTab(null)}><X size={17}/></Button></header>
  <div className="editor-file"><FileCode2 size={15}/><span>{mockup.name}</span><small>변경 #{mockup.revision}</small></div>
  <nav className="editor-panel-tabs"><button className={tab==='ai'?'active':''} onClick={()=>onTab('ai')}><Sparkles size={14}/>AI 수정</button><button className={tab==='history'?'active':''} onClick={()=>onTab('history')}><History size={14}/>이력 · 버전</button></nav>
  <div className="editor-panel-scroll">
   {tab==='ai'?<>
    <div className="ollama-connection"><button className="connection-summary" onClick={()=>setSettingsOpen(!settingsOpen)}><span className={`connection-dot ${connected?'online':''}`}/><span>Ollama <small>{connected?'연결됨':'연결 필요'}</small></span><Settings2 size={15}/></button>
     {settingsOpen&&<div className="connection-fields"><label htmlFor="ollama-url">서버 주소</label><Input id="ollama-url" value={address} disabled={generating} onChange={e=>{setAddress(e.target.value);setConnected(false);}} spellCheck={false}/><Button variant="outline" disabled={checking||generating} onClick={connect}>{checking?<Loader2 className="spin" size={14}/>:<Plug size={14}/>}연결하고 모델 불러오기</Button>{connectionIssue&&<p className="editor-error" role="alert">{connectionIssue}</p>}<details className="ollama-help"><summary>연결이 안 될 때<ChevronDown size={13}/></summary><p>Ollama를 실행하고 이 사이트의 연결을 허용해 주세요. 브라우저에서 로컬 네트워크 권한을 물으면 허용해야 합니다.</p><code>{command}</code><button onClick={async()=>{try{await navigator.clipboard.writeText(command);setNotice('연결 명령을 복사했어요.');}catch{setError('명령을 선택해서 복사해 주세요.');}}}><Copy size={12}/>명령 복사</button><p>이미 실행 중이면 종료 후 위 설정으로 다시 시작해 주세요.</p><a href="https://docs.ollama.com/faq#how-can-i-allow-additional-web-origins-to-access-ollama" target="_blank" rel="noreferrer">Ollama 연결 안내 ↗</a></details></div>}
     {connected&&<div className="model-select"><label>사용할 모델</label><Select value={model} onValueChange={selectModel} disabled={generating}><SelectTrigger aria-label="Ollama 모델"><SelectValue placeholder="모델 선택"/></SelectTrigger><SelectContent>{models.map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select></div>}
    </div>
    <div className="ai-prompt"><label htmlFor="ai-edit-prompt">어떻게 바꿔볼까요?</label><p>필요한 코드를 찾아 부분 수정하고 화면을 검사합니다.</p><Textarea id="ai-edit-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={generating||busy} placeholder="예: 전체 배경을 어둡게 바꾸고, 주요 버튼은 라임색으로 강조해줘." maxLength={3000}/><div className="ai-prompt-footer"><span><Monitor size={12}/>{screenName}</span><small>{prompt.length}/3,000</small></div></div>
    {generating?<div className="generation-progress" role="status"><div><Loader2 className="spin" size={18}/><strong>목업을 부분 수정하고 있어요</strong></div><p>{steps[steps.length-1]?.label||'작업을 준비하고 있어요.'}</p><Button variant="outline" onClick={()=>controller.current?.abort()}><Square size={12}/>작업 중단</Button></div>:!candidate?<Button className="generate-button" disabled={!connected||!ready||!prompt.trim()||busy} onClick={generate}><Sparkles size={16}/>수정안 만들기<ArrowRight size={15}/></Button>:null}
    {steps.length>0&&(generating||candidate||error)&&<details className="agent-activity" open={generating||undefined}><summary><span>작업 과정</span><small>{steps.filter(s=>s.status==='done'&&s.tool!=='model').length}단계 완료</small><ChevronDown size={13}/></summary><ol>{steps.map(s=><li key={s.id} className={`agent-step ${s.status}`}><span>{s.status==='running'?<Loader2 className="spin" size={13}/>:s.status==='error'?<AlertCircle size={13}/>:<Check size={13}/>}</span><div><strong>{s.label}</strong>{s.detail&&<p>{s.detail}</p>}</div></li>)}</ol></details>}
    {candidate&&<div className="candidate-card"><div className="candidate-heading"><span><Check size={15}/>수정안이 준비됐어요</span><small>적용 전</small></div><p>{candidate.summary}</p><div className="candidate-check"><Check size={13}/>{candidate.checkedScreens}개 화면 검사 · 새 실행 오류 없음</div><div className="candidate-meta"><span>{mockup.screens.length!==candidate.screens.length?`${mockup.screens.length} → `:''}{candidate.screens.length}개 화면</span><span>{candidate.model}</span></div><details className="agent-diff"><summary>부분 수정 내역 · {candidate.edits.length}회<ChevronDown size={13}/></summary>{candidate.edits.map(edit=><div className="agent-diff-entry" key={edit.revision}><small>수정 {edit.revision} · {edit.line}번째 줄 근처</small><label>변경 전</label><pre className="removed">{edit.before}</pre><label>변경 후</label><pre className="added">{edit.after}</pre></div>)}</details><div className="candidate-preview"><button className={!preview?'active':''} onClick={()=>onPreview(null)}>현재 목업</button><button className={preview?.kind==='ai'?'active':''} onClick={()=>onPreview({mockupId:mockup.id,html:candidate.html,screens:candidate.screens,title:'AI 수정안 · 적용 전',kind:'ai'})}>수정안 보기</button></div>{conflict&&<p className="editor-error">다른 변경이 먼저 적용됐어요. 최신 목업으로 수정안을 다시 만들어 주세요.</p>}<Button className="apply-button" disabled={busy||!!conflict} onClick={apply}>{busy?<Loader2 className="spin" size={15}/>:<Check size={15}/>}적용하고 이력 저장</Button><button className="discard-candidate" disabled={busy} onClick={()=>{setCandidate(null);onPreview(null);setError('');}}>수정안 버리기</button></div>}
    <p className="ai-local-note">모델이 요청한 코드 조각과 검사 결과를 이 브라우저에서 Ollama로 직접 전송합니다. 적용한 HTML과 변경 이력은 워크스페이스에 저장됩니다.</p>
   </>:<>
    <div className="history-actions"><div><h3>필요한 순간을 버전으로.</h3><p>변경은 자동 저장되고, 이름을 붙인 버전은 따로 모입니다.</p></div><Button onClick={()=>{setNameTarget(mockup.revision);setVersionName('');setError('');}}><Bookmark size={15}/>현재 버전 저장</Button></div>
    {nameTarget!==null&&<form className="version-name-form" onSubmit={e=>{e.preventDefault();saveVersion();}}><label htmlFor="version-name">변경 #{nameTarget}에 이름 붙이기</label><Input id="version-name" autoFocus value={versionName} onChange={e=>setVersionName(e.target.value)} placeholder="예: 첫 리뷰 완료" maxLength={80}/><div><Button variant="ghost" type="button" onClick={()=>setNameTarget(null)}>취소</Button><Button type="submit" disabled={busy||!versionName.trim()}>{busy?<Loader2 className="spin" size={14}/>:<Bookmark size={14}/>}버전 저장</Button></div></form>}
    {preview?.kind==='revision'&&<div className="restore-card"><span><History size={15}/>{preview.title} 미리보기</span><p>복원해도 기존 이력은 남습니다. 복원한 내용은 새 변경으로 기록됩니다.</p><Button disabled={busy||preview.revision===mockup.revision} onClick={restore}>{busy?<Loader2 className="spin" size={14}/>:<RotateCcw size={14}/>}이 내용으로 복원</Button><button onClick={()=>onPreview(null)}><ArrowLeft size={12}/>현재 목업으로 돌아가기</button></div>}
    <div className="history-filters"><button className={!namedOnly?'active':''} onClick={()=>setNamedOnly(false)}>모든 변경</button><button className={namedOnly?'active':''} onClick={()=>setNamedOnly(true)}>저장한 버전</button><Button variant="ghost" size="icon-sm" aria-label="이력 새로고침" onClick={()=>loadHistory()} disabled={historyLoading}><RotateCcw size={14}/></Button></div>
    {historyLoading&&!history.length&&<div className="history-empty"><Loader2 className="spin" size={20}/>이력을 불러오는 중이에요</div>}
    {!historyLoading&&!history.length&&<div className="history-empty"><Bookmark size={27}/><strong>아직 저장한 버전이 없어요</strong><p>리뷰를 마친 순간에 이름을 붙여보세요.</p></div>}
    <ol className="revision-list">{history.map(item=><li key={item.id} className={`${item.revision===mockup.revision?'current':''} ${preview?.kind==='revision'&&preview.revision===item.revision?'previewing':''}`}><div className="revision-marker">{item.label?<Bookmark size={14}/>:item.kind==='restore'?<RotateCcw size={14}/>:item.kind==='ai'?<Sparkles size={14}/>:<FileCode2 size={14}/>}</div><div className="revision-detail"><div className="revision-top"><span>{item.label?`v${item.version_number}`:`변경 #${item.revision}`}</span>{item.revision===mockup.revision&&<small>현재</small>}<time>{date(item.created_at)}</time></div><h4>{item.label|| (item.kind==='upload'?'처음 업로드한 원본':item.kind==='restore'?`변경 #${item.restored_from}에서 복원`:item.prompt)}</h4>{item.label&&item.prompt&&<p>{item.prompt}</p>}<div className="revision-author">{item.author}{item.model&&` · ${item.model}`}</div><div className="revision-actions"><button disabled={busy} onClick={()=>inspectRevision(item)}>미리보기<ArrowRight size={12}/></button>{!item.label&&<button disabled={busy} onClick={()=>{setNameTarget(item.revision);setVersionName('');}}>버전으로 저장</button>}</div></div></li>)}</ol>
    {nextBefore!==null&&<Button className="history-more" variant="outline" disabled={historyLoading} onClick={()=>loadHistory(true,nextBefore)}>이전 변경 더 보기</Button>}

   </>}
   {error&&<p className="editor-error" role="alert">{error}</p>}{notice&&<p className="editor-notice" role="status"><Check size={14}/>{notice}</p>}
  </div>
  <footer className="editor-panel-footer"><span className="small-status-dot"/>{tab==='ai'?'적용하기 전까지 현재 목업은 바뀌지 않아요':'복원해도 이전 변경 이력은 보존돼요'}</footer>
 </aside>;
}
