'use client';
import {useCallback,useEffect,useMemo,useRef,useState,memo} from 'react';
import {ArrowUpRight,Check,CheckCheck,ChevronDown,ChevronRight,CornerDownRight,ExternalLink,FileCode2,Hand,HelpCircle,Layers,LayoutGrid,Link2,Loader2,Maximize,Menu,MessageCircle,MousePointer2,Plus,Send,Settings2,Upload,Users,X,Minus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Comment,Screen,WorkspaceState} from '@/lib/types';
import {detectScreens,screenHtml} from '@/lib/html';
import {demoHtml} from '@/lib/demo';

const W=740,H=880,GAP=70;
const EMPTY:WorkspaceState={projects:[],mockups:[],comments:[],people:[]};
type Mode='select'|'hand'|'comment'|'interact';
type Pin={mockupId:string;screenIndex:number;x:number;y:number};
type Pending={file:File;html:string;screens:Screen[]};
const Frame=memo(function Frame({html,screen,interactive}:{html:string;screen:Screen;interactive:boolean}){
 const src=useMemo(()=>screenHtml(html,screen),[html,screen]);
 return <iframe title={`${screen.name} 목업`} srcDoc={src} sandbox="allow-scripts" referrerPolicy="no-referrer" tabIndex={interactive?0:-1} style={{width:W,height:H,pointerEvents:interactive?'auto':'none'}}/>;
});
async function api(payload:Record<string,unknown>){const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {id:string;error?:string;html:string};if(!r.ok)throw Error(d.error||'요청을 처리하지 못했어요.');return d;}
const time=(n:number)=>new Date(n).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});
function IconButton({label,children,onClick,active=false,className=''}:{label:string;children:React.ReactNode;onClick:()=>void;active?:boolean;className?:string}){return <Button variant="ghost" size="icon" title={label} aria-label={label} aria-pressed={active} className={`icon-button ${active?'is-active':''} ${className}`} onClick={onClick}>{children}</Button>}

export default function Workspace(){
 const [data,setData]=useState<WorkspaceState>(EMPTY);
 const [projectId,setProjectId]=useState('demo-luma');
 const [mockupId,setMockupId]=useState('');
 const [htmls,setHtmls]=useState<Record<string,string>>({'demo-dashboard':demoHtml});
 const [compactNav,setCompactNav]=useState(false);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [mode,setMode]=useState<Mode>('select'),[zoom,setZoom]=useState(.4),[pan,setPan]=useState({x:40,y:100});
 const [selectedScreen,setSelectedScreen]=useState(0),[selectedComment,setSelectedComment]=useState<string|null>(null);
 const [panel,setPanel]=useState<'comments'|'chat'>('comments'),[resolved,setResolved]=useState(false),[panelOpen,setPanelOpen]=useState(true),[navOpen,setNavOpen]=useState(false);
 const [pin,setPin]=useState<Pin|null>(null),[draft,setDraft]=useState(''),[reply,setReply]=useState(''),[chat,setChat]=useState(''),[saving,setSaving]=useState(false);
 const [uploadOpen,setUploadOpen]=useState(false),[pending,setPending]=useState<Pending[]>([]),[uploadError,setUploadError]=useState(''),[uploading,setUploading]=useState(false),[dragOver,setDragOver]=useState(false);
 const [projectOpen,setProjectOpen]=useState(false),[newProject,setNewProject]=useState('');
 const [helpOpen,setHelpOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[profileDraft,setProfileDraft]=useState('');
 const [name,setName]=useState('방문자'),[sessionId,setSessionId]=useState(''),[color,setColor]=useState('#5b8664');
 const [link,setLink]=useState('');
 const canvas=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),pointer=useRef<{x:number|null;y:number|null}>({x:null,y:null});
 const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),space=useRef(false),projectRef=useRef(projectId);
 const lastState=useRef(''),busyPoll=useRef(false),initialized=useRef(false);
 const project=data.projects.find(p=>p.id===projectId);
 const mockup=data.mockups.find(m=>m.id===mockupId)||data.mockups[0];
 const screens=mockup?.screens||[];
 const threads=data.comments.filter(c=>!c.parent_id&&c.mockup_id);
 const projectChats=data.comments.filter(c=>!c.parent_id&&!c.mockup_id);
 const visibleThreads=threads.filter(c=>Boolean(c.resolved)===resolved);
 const activeThreads=threads.filter(c=>!c.resolved);
 const others=data.people.filter(p=>p.id!==sessionId);
 const allScreens=data.mockups.reduce((n,m)=>n+m.screens.length,0);
 const showToast=(message:string)=>setToast(message);
 useEffect(()=>{const update=()=>setCompactNav(window.innerWidth<=850);update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update);},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 const refresh=useCallback(async()=>{
  if(busyPoll.current)return;busyPoll.current=true;const id=projectRef.current;
  try{const r=await fetch('/api/workspace?project='+encodeURIComponent(id),{cache:'no-store'});const d=await r.json() as WorkspaceState & {error?:string};if(!r.ok)throw Error(d.error);if(id!==projectRef.current)return;const hash=JSON.stringify(d);if(hash!==lastState.current){lastState.current=hash;setData(d);}setError('');setLoading(false);}
  catch(e){setError(e instanceof Error?e.message:'연결이 끊겼어요. 다시 시도해 주세요.');setLoading(false);}finally{busyPoll.current=false;}
 },[]);
 useEffect(()=>{
  if(window.innerWidth<630)setPanelOpen(false);
  const qs=new URLSearchParams(location.search);const id=qs.get('project')||'demo-luma';projectRef.current=id;setProjectId(id);
  let identity:{name:string;color:string}|null=null;try{identity=JSON.parse(localStorage.getItem('speck-profile')||'null');}catch{}
  const sid=crypto.randomUUID();const profile=identity||{name:'방문자 '+sid.slice(0,4),color:['#648854','#936eac','#4d8d9b','#b98058'][Math.floor(Math.random()*4)]};setSessionId(sid);setName(profile.name);setColor(profile.color);try{localStorage.setItem('speck-profile',JSON.stringify(profile));}catch{}
  if(!initialized.current){initialized.current=true;api({action:'init'}).then(refresh).catch(e=>{setError(e.message);setLoading(false);});}
  const timer=setInterval(()=>{if(!document.hidden)refresh();},1800);return()=>clearInterval(timer);
 },[refresh]);
 useEffect(()=>{projectRef.current=projectId;lastState.current='';refresh();setMockupId('');setPin(null);setSelectedComment(null);setSelectedScreen(0);setReply('');setDraft('');setChat('');},[projectId,refresh]);
 useEffect(()=>{
  if(!sessionId)return;
  const send=()=>{if(!document.hidden)api({action:'presence',projectId,sessionId,name,color,...pointer.current}).catch(()=>{});};
  send();const t=setInterval(send,1800);return()=>clearInterval(t);
 },[projectId,sessionId,name,color]);
 useEffect(()=>{
  if(!mockup||htmls[mockup.id])return;let active=true;
  fetch('/api/mockups/'+encodeURIComponent(mockup.id)).then(async r=>{const d=await r.json() as {id:string;error?:string;html:string};if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(active)setHtmls(h=>({...h,[mockup.id]:d.html}));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
 },[mockup,htmls]);
 const fit=useCallback(()=>{if(!canvas.current||!screens.length)return;const rect=canvas.current.getBoundingClientRect();const width=screens.length*W+(screens.length-1)*GAP;const z=Math.min((rect.width-72)/width,(rect.height-200)/H,.8);const clamped=Math.max(.08,z);setZoom(clamped);setPan({x:(rect.width-width*clamped)/2,y:Math.max(96,(rect.height-H*clamped)/2-12)});},[screens.length]);
 useEffect(()=>{fit();const obs=new ResizeObserver(fit);if(canvas.current)obs.observe(canvas.current);return()=>obs.disconnect();},[fit,mockup?.id,panelOpen]);
 function adjustZoom(next:number,anchor?:{x:number;y:number}){const z=Math.max(.08,Math.min(2,next));const rect=canvas.current?.getBoundingClientRect();const center=anchor||{x:(rect?.width||800)/2,y:(rect?.height||700)/2};setPan(p=>({x:center.x-(center.x-p.x)*z/zoom,y:center.y-(center.y-p.y)*z/zoom}));setZoom(z);}
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const rect=el.getBoundingClientRect();adjustZoom(zoom*Math.exp(-e.deltaY*.006),{x:e.clientX-rect.left,y:e.clientY-rect.top});}else setPan(p=>({x:p.x-e.deltaX,y:p.y-e.deltaY}));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);});
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(t.closest('input,textarea,[contenteditable=true]')||uploadOpen||projectOpen||helpOpen||shareOpen||profileOpen)return;if(e.code==='Space'){e.preventDefault();space.current=true;canvas.current?.classList.add('grabbing');}if(e.key.toLowerCase()==='c'){setMode('comment');setPanel('comments');setPanelOpen(window.innerWidth>=630);}if(e.key.toLowerCase()==='v')setMode('select');if(e.key.toLowerCase()==='h')setMode('hand');if(e.key==='1'){e.preventDefault();fit();}if(e.key==='+'||e.key==='=')adjustZoom(zoom*1.2);if(e.key==='-')adjustZoom(zoom/1.2);if(e.key==='Escape'){setPin(null);setSelectedComment(null);setMode('select');}};const up=(e:KeyboardEvent)=>{if(e.code==='Space'){space.current=false;canvas.current?.classList.remove('grabbing');}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};});
 function changeProject(id:string){setProjectId(id);setNavOpen(false);history.replaceState(null,'','?project='+encodeURIComponent(id));}
 function pointerDown(e:React.PointerEvent){if((e.target as HTMLElement).closest('button,input,textarea,.canvas-toolbar,.zoom-controls'))return;if(mode==='hand'||space.current||e.button===1||(e.target as HTMLElement).dataset.canvas==='true'){e.preventDefault();drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId);canvas.current?.classList.add('grabbing');}}
 function pointerMove(e:React.PointerEvent){const rect=canvas.current?.getBoundingClientRect();if(rect)pointer.current={x:(e.clientX-rect.left-pan.x)/zoom,y:(e.clientY-rect.top-pan.y)/zoom};if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y});}
 function pointerUp(){drag.current=null;canvas.current?.classList.remove('grabbing');}
 function placePin(e:React.MouseEvent,index:number){if(mode==='hand'||space.current)return;setSelectedScreen(index);if(mode==='comment'&&mockup){const r=e.currentTarget.getBoundingClientRect();setPin({mockupId:mockup.id,screenIndex:index,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height});setSelectedComment(null);setDraft('');setPanel('comments');setPanelOpen(true);}}
 function focusThread(c:Comment){setMockupId(c.mockup_id||mockup?.id||'');setSelectedScreen(c.screen_index||0);setSelectedComment(c.id);setPin(null);setPanel('comments');setPanelOpen(true);setReply('');}
 async function submitComment(kind:'pin'|'reply'|'chat'){
  const body=kind==='pin'?draft:kind==='reply'?reply:chat;if(!body.trim()||saving)return;setSaving(true);
  try{const result=await api({action:'comment',projectId,author:name,body,...(kind==='pin'?pin:{}),...(kind==='reply'?{parentId:selectedComment}:{})});if(kind==='pin'){setPin(null);setDraft('');setSelectedComment(result.id);setMode('select');}if(kind==='reply')setReply('');if(kind==='chat')setChat('');await refresh();}catch(e){showToast((e as Error).message);}finally{setSaving(false);}
 }
 async function toggleResolve(c:Comment){try{await api({action:'resolve',projectId,id:c.id,resolved:!c.resolved});await refresh();showToast(c.resolved?'코멘트를 다시 열었어요.':'코멘트를 해결했어요.');}catch(e){showToast((e as Error).message);}}
 async function pickFiles(files:FileList|File[]|null){
  if(!files)return;setUploadError('');const items:Pending[]=[];
  for(const file of Array.from(files)){if(!/\.html?$/i.test(file.name)){setUploadError('HTML 파일(.html, .htm)을 선택해 주세요.');continue;}if(file.size>5*1024*1024||!file.size){setUploadError('비어 있지 않은 5MB 이하 파일을 선택해 주세요.');continue;}const html=await file.text();items.push({file,html,screens:detectScreens(html)});}
  setPending(p=>[...p,...items].slice(0,10));
 }
 async function upload(){setUploading(true);setUploadError('');const remaining=[...pending];try{let lastId='';for(const item of pending){const form=new FormData();form.set('file',item.file);form.set('projectId',projectId);form.set('screens',JSON.stringify(item.screens));const r=await fetch('/api/mockups',{method:'POST',body:form});const d=await r.json() as {id:string;error?:string;html:string};if(!r.ok)throw Error(d.error);setHtmls(h=>({...h,[d.id]:item.html}));lastId=d.id;remaining.shift();}setPending([]);setUploadOpen(false);await refresh();setMockupId(lastId);showToast('목업을 업로드했어요. 화면을 함께 리뷰해 보세요.');}catch(e){setPending(remaining);setUploadError((e as Error).message);await refresh();}finally{setUploading(false);}}
 async function createProject(){if(!newProject.trim())return;setSaving(true);try{const d=await api({action:'project',name:newProject});setProjectOpen(false);setNewProject('');changeProject(d.id);showToast('새 프로젝트가 준비됐어요. HTML 목업을 올려보세요.');}catch(e){showToast((e as Error).message);}finally{setSaving(false);}}
 function openShare(){setLink(location.origin+'/?project='+encodeURIComponent(projectId));setShareOpen(true);}
 async function copyLink(){try{await navigator.clipboard.writeText(link);showToast('프로젝트 링크를 복사했어요.');}catch{showToast('링크를 선택해서 직접 복사해 주세요.');}}
 const getScreenName=(c:Comment)=>data.mockups.find(m=>m.id===c.mockup_id)?.screens[c.screen_index||0]?.name||'화면';
 return <main className="workspace">
  <aside inert={compactNav&&!navOpen} className={`sidebar ${navOpen?'mobile-open':''}`}>
   <a className="wordmark" href="/" aria-label="Speck 홈"><img src="/favicon.svg" alt=""/><span>speck<span className="wordmark-dot">.</span></span><span className="beta">BETA</span></a>
   <div className="workspace-label"><div className="workspace-monogram">S</div><div><strong>우리 팀 워크스페이스</strong><span>함께 만드는 더 나은 화면</span></div></div>
   <div className="sidebar-section-heading"><span>프로젝트</span><IconButton label="새 프로젝트 만들기" onClick={()=>setProjectOpen(true)}><Plus size={16}/></IconButton></div>
   <nav className="projects-nav" aria-label="프로젝트">
    {data.projects.map(p=><div key={p.id}><button className={`project-item ${projectId===p.id?'active':''}`} onClick={()=>changeProject(p.id)}><span className="project-color" style={{background:p.color}}/><span>{p.name}</span><span className="count">{p.count||0}</span>{projectId===p.id?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button>{projectId===p.id&&<div className="project-files">{data.mockups.map(m=><button className={`file-item ${mockup?.id===m.id?'active':''}`} key={m.id} onClick={()=>{setMockupId(m.id);setSelectedScreen(0);setNavOpen(false);}}><FileCode2 size={15}/><span>{m.name.replace(/\.html?$/i,'')}</span><small>{m.screens.length}</small></button>)}<button className="add-mockup" onClick={()=>setUploadOpen(true)}><Plus size={14}/>목업 추가</button></div>}</div>)}
    {loading&&<div className="sidebar-loading"><Loader2 className="spin" size={16}/>프로젝트 불러오는 중</div>}
   </nav>
   <div className="screen-section"><div className="sidebar-section-heading"><span>화면</span><span className="text-count">{screens.length.toString().padStart(2,'0')}</span></div>{screens.map((s,i)=><button key={i} className={`screen-item ${selectedScreen===i?'active':''}`} onClick={()=>{setSelectedScreen(i);setNavOpen(false);}}><LayoutGrid size={15}/><span>{s.name}</span><span className="screen-number">{(i+1).toString().padStart(2,'0')}</span></button>)}</div>
   <div className="sidebar-bottom"><div className="review-tip"><div className="tip-icon"><MessageCircle size={18}/><span>작은 의견이, 더 좋은 화면으로.</span></div><p><kbd>C</kbd> 를 누르고 화면에 핀을 찍어보세요.</p></div><button className="help-link" onClick={()=>setHelpOpen(true)}><HelpCircle size={16}/>도움말과 단축키<ArrowUpRight size={14}/></button><button className="profile" onClick={()=>{setProfileDraft(name);setProfileOpen(true);}}><span className="avatar" style={{background:color+'25',color}}>{name.slice(0,1)}</span><span><strong>{name}</strong><small>프로필 이름 변경</small></span><Settings2 size={16}/></button></div>
  </aside>
  {navOpen&&<button className="mobile-scrim" aria-label="메뉴 닫기" onClick={()=>setNavOpen(false)}/>}
  <section className="main-workspace">
   <header className="topbar"><div className="breadcrumb"><IconButton label="프로젝트 메뉴" className="mobile-menu" onClick={()=>setNavOpen(!navOpen)}><Menu/></IconButton><span className="breadcrumb-home">워크스페이스</span><ChevronRight className="breadcrumb-home" size={14}/><strong>{project?.name||'워크스페이스'}</strong>{projectId==='demo-luma'&&<span className="sample-badge">샘플</span>}</div><div className="topbar-actions"><div className={`live-status ${error?'offline':''}`} title={error?'연결 재시도 중':'약 2초마다 변경 사항을 동기화해요'}><span/>{error?'재연결 중':'라이브'}</div><div className="collaborators"><span className="avatar" style={{background:color+'25',color}} title={`${name} (나)`}>{name.slice(0,1)}</span>{others.slice(0,3).map(p=><span key={p.id} className="avatar" style={{background:p.color+'25',color:p.color}} title={p.name}>{p.name.slice(0,1)}</span>)}</div><Button variant="outline" className="share-button" aria-label="프로젝트 공유" onClick={openShare}><Link2 size={15}/><span>공유</span></Button><Button className="upload-button" aria-label="HTML 업로드" onClick={()=>setUploadOpen(true)}><Plus size={17}/><span>HTML 업로드</span></Button></div></header>
   <div className="subbar"><div className="view-tabs"><button className="active"><LayoutGrid size={15}/>캔버스<span>{allScreens}</span></button><span className="view-tab-detail">파일을 넘어, 같은 화면으로.</span></div><div className="subbar-right"><span><Layers size={14}/>탭 자동 분리</span><IconButton label={panelOpen?'코멘트 패널 닫기':'코멘트 패널 열기'} active={panelOpen} onClick={()=>setPanelOpen(!panelOpen)}><MessageCircle size={17}/></IconButton></div></div>
   {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={refresh}>다시 시도</button></div>}
   <div className="editor-body">
    <div className={`canvas mode-${mode}`} ref={canvas} data-canvas="true" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onPointerLeave={()=>{pointer.current={x:null,y:null};}}>
     <div className="canvas-heading"><div className="canvas-file-icon"><FileCode2 size={20}/></div><div><h1>{mockup?mockup.name.replace(/\.html?$/i,''):project?.name||'워크스페이스'}</h1><p>{mockup?`${screens.length}개의 화면 · ${mockup.id==='demo-dashboard'?'샘플 목업':new Date(mockup.created_at).toLocaleDateString('ko-KR')+' 업로드'}`:'첫 번째 목업을 기다리고 있어요'}</p></div><span className="canvas-file-tag">HTML</span></div>
     {loading?<div className="canvas-empty"><Loader2 className="spin"/><h2>워크스페이스를 여는 중이에요</h2></div>:!mockup?<div className="canvas-empty"><div className="empty-stack"><FileCode2 size={34}/></div><h2>첫 화면에서 시작하는 대화</h2><p>HTML 목업을 올리면 탭별로 화면이 펼쳐져요.<br/>팀과 함께 보고, 원하는 위치에 의견을 남겨보세요.</p><Button onClick={()=>setUploadOpen(true)}><Upload size={16}/>첫 목업 업로드</Button></div>:<div className="canvas-world" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
      {screens.map((screen,i)=><div className={`artboard ${selectedScreen===i?'selected':''}`} key={mockup.id+'-'+i} style={{left:i*(W+GAP),width:W}}><button className="artboard-label" onClick={()=>setSelectedScreen(i)}><span className="artboard-index">{String(i+1).padStart(2,'0')}</span><span>{screen.name}</span><span className="artboard-dimensions">740 × 880</span></button><div className="artboard-body" style={{width:W,height:H}} onClick={e=>placePin(e,i)}>{htmls[mockup.id]?<Frame html={htmls[mockup.id]} screen={screen} interactive={mode==='interact'}/>:<div className="frame-loading"><Loader2 className="spin"/>화면 불러오는 중</div>}{mode!=='interact'&&<div className="frame-overlay"/>}{threads.filter(c=>c.mockup_id===mockup.id&&c.screen_index===i&&!c.resolved).map((c)=><button key={c.id} className={`comment-pin ${selectedComment===c.id?'selected':''}`} style={{left:`${(c.x||0)*100}%`,top:`${(c.y||0)*100}%`,transform:`translate(-20%,-85%) scale(${1/zoom})`}} title={`${c.author}: ${c.body}`} aria-label={`코멘트 ${threads.indexOf(c)+1} 보기`} onClick={e=>{e.stopPropagation();focusThread(c);}}>{threads.indexOf(c)+1}</button>)}{pin?.mockupId===mockup.id&&pin.screenIndex===i&&<span className="comment-pin new-pin" style={{left:pin.x*100+'%',top:pin.y*100+'%',transform:`translate(-20%,-85%) scale(${1/zoom})`}}><Plus size={15}/></span>}</div></div>)}
      {others.filter(p=>p.x!==null&&p.y!==null).map(p=><div key={p.id} className="remote-cursor" style={{left:p.x!,top:p.y!,color:p.color,transform:`scale(${1/zoom})`}}><MousePointer2 size={19} fill={p.color}/><span style={{background:p.color}}>{p.name}</span></div>)}
     </div>}
     <div className="canvas-footer-info"><span className="canvas-dot"/>{screens.length}개 화면<span className="footer-separator">/</span>{mode==='comment'?'코멘트를 남길 위치를 클릭하세요':mode==='interact'?'목업의 버튼을 직접 눌러보세요':'Space + 드래그로 이동'}</div>
     <div className="canvas-toolbar" role="toolbar" aria-label="캔버스 도구"><IconButton label="선택 (V)" active={mode==='select'} onClick={()=>setMode('select')}><MousePointer2 size={19}/></IconButton><IconButton label="이동 (H)" active={mode==='hand'} onClick={()=>setMode('hand')}><Hand size={19}/></IconButton><span className="tool-divider"/><IconButton label="핀 코멘트 (C)" active={mode==='comment'} onClick={()=>{setMode('comment');setPanel('comments');setPanelOpen(window.innerWidth>=630);}}><MessageCircle size={19}/></IconButton><IconButton label="목업 직접 조작" active={mode==='interact'} onClick={()=>{setMode('interact');setPin(null);}}><ExternalLink size={18}/></IconButton></div>
     <div className="zoom-controls"><IconButton label="축소" onClick={()=>adjustZoom(zoom/1.2)}><Minus size={16}/></IconButton><button className="zoom-value" title="100%로 확대" onClick={()=>adjustZoom(1)}>{Math.round(zoom*100)}%</button><IconButton label="확대" onClick={()=>adjustZoom(zoom*1.2)}><Plus size={16}/></IconButton><span/><IconButton label="전체 화면 맞추기 (1)" onClick={fit}><Maximize size={16}/></IconButton></div>
    </div>
    {panelOpen&&<aside className="comments-panel"><div className="panel-tabs"><button className={panel==='comments'?'active':''} onClick={()=>setPanel('comments')}>코멘트<span>{activeThreads.length}</span></button><button className={panel==='chat'?'active':''} onClick={()=>setPanel('chat')}>팀 채팅{projectChats.length>0&&<span>{projectChats.length}</span>}</button><IconButton label="패널 닫기" onClick={()=>setPanelOpen(false)}><X size={16}/></IconButton></div>
     {panel==='comments'?<><div className="comment-filters"><button className={!resolved?'active':''} onClick={()=>setResolved(false)}>진행 중<span>{activeThreads.length}</span></button><button className={resolved?'active':''} onClick={()=>setResolved(true)}>해결됨<span>{threads.length-activeThreads.length}</span></button></div><div className="comments-scroll">
      {pin&&<div className="new-comment-card"><div className="new-comment-heading"><span><MessageCircle size={15}/>새 코멘트</span><IconButton label="새 코멘트 취소" onClick={()=>setPin(null)}><X size={15}/></IconButton></div><small>{mockup?.screens[pin.screenIndex]?.name}에 남기는 피드백</small><Textarea autoFocus aria-label="핀 코멘트 입력" placeholder="어떤 의견이 있으신가요?" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={3000}/><Button disabled={!draft.trim()||saving} onClick={()=>submitComment('pin')}>{saving?<Loader2 className="spin" size={14}/>:<Send size={14}/>}코멘트 남기기</Button></div>}
      {visibleThreads.length===0&&!pin&&<div className="comments-empty"><CheckCheck size={29}/><h3>{resolved?'아직 해결된 코멘트가 없어요':'모든 의견을 확인했어요'}</h3><p>{resolved?'논의를 마친 코멘트가 여기에 모여요.':'새로운 의견이 있다면 화면에 핀을 찍어보세요.'}</p></div>}
      {visibleThreads.map((c)=>{const replies=data.comments.filter(r=>r.parent_id===c.id);const selected=selectedComment===c.id;return <article key={c.id} className={`comment-card ${selected?'selected':''}`}><div className="comment-person"><span className={`avatar ${c.id.startsWith('guide-')?'guide-avatar':''}`}>{c.id.startsWith('guide-')?<img src="/favicon.svg" alt=""/>:c.author.slice(0,1)}</span><div><strong>{c.author}</strong><small>{c.id.startsWith('guide-')?'사용 가이드':time(c.created_at)}</small></div><IconButton label={c.resolved?'코멘트 다시 열기':'코멘트 해결하기'} active={Boolean(c.resolved)} onClick={()=>toggleResolve(c)}><Check size={16}/></IconButton></div><button className="comment-content" onClick={()=>focusThread(c)}><span className="comment-location"><span>{threads.indexOf(c)+1}</span>{getScreenName(c)}<ArrowUpRight size={12}/></span><p>{c.body}</p></button><button className="reply-link" onClick={()=>focusThread(c)}><MessageCircle size={13}/>{replies.length?`답글 ${replies.length}개`:'답글 남기기'}</button>{selected&&<div className="reply-thread">{replies.map(r=><div className="reply-item" key={r.id}><CornerDownRight size={13}/><div><strong>{r.author}<small>{time(r.created_at)}</small></strong><p>{r.body}</p></div></div>)}<div className="reply-input"><Textarea aria-label="답글 입력" placeholder="답글을 남겨보세요" value={reply} onChange={e=>setReply(e.target.value)} maxLength={3000}/><Button size="icon-sm" title="답글 보내기" aria-label="답글 보내기" disabled={!reply.trim()||saving} onClick={()=>submitComment('reply')}><Send size={14}/></Button></div></div>}</article>})}
     </div><div className="panel-bottom"><div><span className="small-status-dot"/>피드백이 실시간으로 모이는 공간</div><button onClick={()=>{setMode('comment');setResolved(false);if(window.innerWidth<630)setPanelOpen(false);showToast('화면에서 의견을 남길 위치를 클릭하세요.');}}><Plus size={16}/>핀 코멘트 추가<kbd>C</kbd></button></div></>:<><div className="chat-intro"><Users size={16}/><span>{others.length+1}명이 이 프로젝트에 참여 중</span></div><div className="comments-scroll chat-list">{projectChats.length===0?<div className="comments-empty"><MessageCircle size={30}/><h3>화면 옆에서 나누는 대화</h3><p>리뷰 일정이나 전체적인 의견을<br/>팀과 이야기해 보세요.</p></div>:projectChats.map(c=><div className={`chat-message ${c.author===name?'mine':''}`} key={c.id}><div><strong>{c.author}</strong><small>{time(c.created_at)}</small></div><p>{c.body}</p></div>)}</div><form className="chat-composer" onSubmit={e=>{e.preventDefault();submitComment('chat');}}><Textarea aria-label="팀 채팅 메시지" placeholder="팀에게 메시지 보내기…" value={chat} onChange={e=>setChat(e.target.value)} maxLength={3000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submitComment('chat');}}}/><div><small>Enter 전송 · Shift + Enter 줄바꿈</small><Button size="icon-sm" aria-label="메시지 보내기" type="submit" disabled={!chat.trim()||saving}><Send size={15}/></Button></div></form></>}
    </aside>}
   </div>
  </section>
  <Dialog open={uploadOpen} onOpenChange={o=>{if(!uploading){setUploadOpen(o);setUploadError('');}}}><DialogContent className="upload-dialog"><DialogHeader><div className="dialog-eyebrow"><FileCode2 size={16}/>HTML TO CANVAS</div><DialogTitle>목업을 펼쳐볼까요?</DialogTitle><DialogDescription><strong>{project?.name}</strong>에 HTML 파일을 업로드하세요.<br/>파일 안의 탭을 찾아 각각의 화면으로 보여드려요.</DialogDescription></DialogHeader><input hidden ref={fileInput} type="file" accept=".html,.htm,text/html" multiple onChange={e=>{pickFiles(e.target.files);e.target.value='';}}/><button className={`dropzone ${dragOver?'drag-over':''}`} onClick={()=>fileInput.current?.click()} onDragOver={e=>{e.preventDefault();setDragOver(true);}} onDragLeave={()=>setDragOver(false)} onDrop={e=>{e.preventDefault();setDragOver(false);pickFiles(e.dataTransfer.files);}}><span className="upload-file-icon"><Upload size={26}/></span><strong>HTML 파일을 여기에 놓아주세요</strong><span>또는 <u>파일 선택</u></span><small>.html, .htm · 파일당 최대 5MB</small></button>{pending.length>0&&<div className="pending-files">{pending.map((p,i)=><div className="pending-file" key={i}><div><FileCode2 size={18}/><strong>{p.file.name}</strong><span>{p.screens.length}개 화면</span><IconButton label={`${p.file.name} 제거`} onClick={()=>setPending(v=>v.filter((_,idx)=>i!==idx))}><X size={14}/></IconButton></div><div className="detected-tabs">{p.screens.map((s,j)=><span key={j}>{s.name}</span>)}</div>{p.screens.length>1&&<button className="merge-screens" onClick={()=>setPending(v=>v.map((item,idx)=>idx===i?{...item,screens:[{name:item.file.name.replace(/\.html?$/i,'')}]}:item))}>한 화면으로 업로드</button>}</div>)}</div>}<p className="upload-note">탭 자동 감지: ARIA 탭, Bootstrap, 일반적인 탭 버튼.<br/>스타일과 스크립트가 포함된 단일 HTML 파일을 권장해요. 로컬의 별도 CSS·이미지 파일은 함께 업로드되지 않아요.</p>{uploadError&&<p className="form-error" role="alert">{uploadError}</p>}<div className="dialog-footer"><span>{pending.length?`${pending.length}개 파일 · ${pending.reduce((n,p)=>n+p.screens.length,0)}개 화면`:'최대 10개 파일을 함께 올릴 수 있어요'}</span><Button onClick={upload} disabled={!pending.length||uploading}>{uploading?<Loader2 className="spin" size={16}/>:<Upload size={16}/>} {uploading?'업로드 중…':'캔버스에 추가'}</Button></div></DialogContent></Dialog>
  <Dialog open={projectOpen} onOpenChange={setProjectOpen}><DialogContent><DialogHeader><DialogTitle>새 프로젝트</DialogTitle><DialogDescription>같이 검토할 목업을 한곳에 모아보세요.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();createProject();}}><label className="field-label" htmlFor="project-name">프로젝트 이름</label><Input id="project-name" autoFocus placeholder="예: 새로운 브랜드 웹사이트" value={newProject} onChange={e=>setNewProject(e.target.value)} maxLength={80}/><div className="dialog-footer"><span/><Button type="submit" disabled={!newProject.trim()||saving}>프로젝트 만들기<Plus size={15}/></Button></div></form></DialogContent></Dialog>
  <Dialog open={shareOpen} onOpenChange={setShareOpen}><DialogContent><DialogHeader><DialogTitle>같은 화면에서 함께 리뷰하세요</DialogTitle><DialogDescription>프로젝트 링크로 코멘트와 채팅이 동기화돼요.<br/>사이트에 접근 권한이 있는 팀원이 참여할 수 있어요.</DialogDescription></DialogHeader><label className="field-label" htmlFor="project-link">프로젝트 링크</label><div className="share-input"><Input id="project-link" value={link} readOnly onFocus={e=>e.target.select()}/><Button onClick={copyLink}><Link2 size={15}/>복사</Button></div><div className="share-note"><Users size={18}/><span>참여자가 들어오면 상단에 표시되고,<br/>캔버스에서 서로의 커서를 볼 수 있어요.</span></div></DialogContent></Dialog>
  <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent><DialogHeader><DialogTitle>어떤 이름으로 참여할까요?</DialogTitle><DialogDescription>팀원들에게 커서와 코멘트의 작성자로 표시돼요.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(profileDraft.trim()){setName(profileDraft.trim());localStorage.setItem('speck-profile',JSON.stringify({name:profileDraft.trim(),color}));setProfileOpen(false);}}}><Input aria-label="참여자 이름" value={profileDraft} onChange={e=>setProfileDraft(e.target.value)} maxLength={24} autoFocus/><div className="dialog-footer"><span/><Button type="submit" disabled={!profileDraft.trim()}>이름 저장</Button></div></form></DialogContent></Dialog>
  <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent><DialogHeader><DialogTitle>화면 사이를 자유롭게</DialogTitle><DialogDescription>자주 사용하는 도구와 단축키를 확인하세요.</DialogDescription></DialogHeader><div className="shortcut-list">{[['선택 도구','V'],['캔버스 이동','H'],['핀 코멘트','C'],['전체 화면 맞추기','1'],['확대 / 축소','+ / −'],['잠깐 이동하기','Space + 드래그'],['트랙패드 확대 / 축소','핀치'],['선택 취소','Esc']].map(([label,key])=><div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div><p className="upload-note">직접 조작 도구 <ExternalLink size={13}/>를 켜면 목업의 버튼과 링크를 눌러볼 수 있어요. 커서, 코멘트와 채팅은 약 2초마다 동기화됩니다.</p></DialogContent></Dialog>
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
 </main>;
}
